name = "AoC2025"
version = "0.1.0"
keywords = ["lea(r)n"]
defaultTargets = ["aoc"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
# linter.flexible = false
# linter.style.commandStart = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "std"
git = "https://github.com/leanprover/std4"
rev = "main"

[[lean_lib]]
name = "AoC2025"

[[lean_exe]]
name = "aoc"
root = "AoC2025"